package com.pedro.activities

class Modelos {
    private val modelosDeCarros = arrayOf(
        "Acura",
        "Alfa Romeo",
        "Aston Martin",
        "Audi",
        "BMW",
        "Buick",
        "Cadillac",
        "Chevrolet",
        "Chrysler",
        "Citroën",
        "Dacia",
        "Daewoo",
        "Dodge",
        "Ferrari",
        "Fiat",
        "Fisker",
        "Ford",
        "Genesis",
        "GMC",
        "Honda",
        "Hyundai",
        "Infiniti",
        "Jaguar",
        "Jeep",
        "Kia",
        "Land Rover",
        "Lexus",
        "Lincoln",
        "Lucid",
        "Maserati",
        "Mazda",
        "McLaren",
        "Mercedes-Benz",
        "Mini",
        "Mitsubishi",
        "Nissan",
        "Pagani",
        "Pininfarina",
        "Polestar",
        "Porsche",
        "RAM",
        "Renault",
        "Rolls-Royce",
        "Saab",
        "Seat",
        "Skoda",
        "Smart",
        "Subaru",
        "Suzuki",
        "Tata",
        "Tesla",
        "Toyota",
        "Volkswagen",
        "Volvo",
        "Wiesmann",
        "Zenos",
        "BYD",
        "Changan",
        "Chery",
        "Dongfeng",
        "Great Wall",
        "Haval",
        "Iveco",
        "Lancia",
        "Landwind",
        "Mahindra",
        "Maruti",
        "NIO",
        "Raptor",
        "Saleen",
        "SRT",
        "Spyker",
        "Vauxhall",
        "Cupra",
        "Karma",
        "Rivian",
        "Sbarro",
        "Zenvo",
        "Sundown",
        "Yamaha",
        "Aurora",
        "Zotye"
    )

    fun getModelosDeCarros(): Array<String> {
        return modelosDeCarros
    }
}
